using System.Collections.Generic;

namespace CFBPredictor.Models
{
    public class NCAA
    {
        private List<Team> FBS = new List<Team>();
        private List<Team> FCS = new List<Team>();
        private List<Conference> Conferences = new List<Conference>();

        private Team AirForce = new Team("Air Force", "MWC", "87");
        private Team Akron = new Team("Akron", "MAC", "47");
        private Team Alabama = new Team("Alabama", "SEC", "73");
        private Team AppalachianState = new Team("Appalachian State", "Sun Belt", "171");
        private Team Arizona = new Team("Arizona", "Pac 12", "57");
        private Team ArizonaState = new Team("Arizona State", "Pac 12", "58");
        private Team Arkansas = new Team("Arkansas", "SEC", "74");
        private Team ArkansasState = new Team("Arkansas State", "Sun Belt", "37");
        private Team Army = new Team("Army", "Independent", "97");
        private Team Auburn = new Team("Auburn", "SEC", "75");
        private Team BallState = new Team("Ball State", "MAC", "48");
        private Team Baylor = new Team("Baylor", "Big 12", "79");
        private Team BoiseState = new Team("Boise State", "MWC", "112");
        private Team BostonCollege = new Team("Boston College", "ACC", "10");
        private Team BowlingGreen = new Team("Bowling Green", "MAC", "49");
        private Team Buffalo = new Team("Buffalo", "MAC", "208");
        private Team BYU = new Team("BYU", "Independent", "88");
        private Team California = new Team("California", "Pac 12", "59");
        private Team CentralMichigan = new Team("Central Michigan", "MAC", "50");
        private Team Charlotte = new Team("Charlotte", "CUSA", "2595");
        private Team Cincinnati = new Team("Cincinnati", "AAC", "98");
        private Team Clemson = new Team("Clemson", "ACC", "1");
        private Team CoastalCarolina = new Team("Coastal Carolina", "Sun Belt", "2316");
        private Team Colorado = new Team("Colorado", "Pac 12", "18");
        private Team ColoradoState = new Team("Colorado State", "MWC", "89");
        private Team Connecticut = new Team("Connecticut", "AAC", "202");
        private Team Duke = new Team("Duke", "ACC", "2");
        private Team EastCarolina = new Team("East Carolina", "AAC", "99");
        private Team EasternMichigan = new Team("Eastern Michigan", "MAC", "51");
        private Team Florida = new Team("Florida", "SEC", "67");
        private Team FloridaAtlantic = new Team("Florida Atlantic", "CUSA", "2294");
        private Team FloridaInternational = new Team("Florida International", "CUSA", "2307");
        private Team FloridaState = new Team("Florida State", "ACC", "3");
        private Team FresnoState = new Team("Fresno State", "MWC", "90");
        private Team Georgia = new Team("Georgia", "SEC", "68");
        private Team GeorgiaSouthern = new Team("Georgia Southern", "Sun Belt", "175");
        private Team GeorgiaState = new Team("Georgia State", "Sun Belt", "2558");
        private Team GeorgiaTech = new Team("Georgia Tech", "ACC", "4");
        private Team Hawaii = new Team("Hawaii", "MWC", "91");
        private Team Houston = new Team("Houston", "AAC", "80");
        private Team Idaho = new Team("Idaho", "Sun Belt", "114");
        private Team Illinois = new Team("Illinois", "Big Ten", "26");
        private Team Indiana = new Team("Indiana", "Big Ten", "27");
        private Team Iowa = new Team("Iowa", "Big Ten", "28");
        private Team IowaState = new Team("Iowa State", "Big 12", "19");
        private Team Kansas = new Team("Kansas", "Big 12", "20");
        private Team KansasState = new Team("Kansas State", "Big 12", "21");
        private Team KentState = new Team("Kent State", "MAC", "52");
        private Team Kentucky = new Team("Kentucky", "SEC", "69");
        private Team LouisianaTech = new Team("Louisiana Tech", "CUSA", "38");
        private Team LouisianaLafayette = new Team("Louisiana Lafayette", "Sun Belt", "45");
        private Team LouisianaMonroe = new Team("Louisiana Monroe", "Sun Belt", "103");
        private Team Louisville = new Team("Louisville", "ACC", "100");
        private Team LSU = new Team("LSU", "SEC", "76");
        private Team Marshall = new Team("Marshall", "CUSA", "176");
        private Team Maryland = new Team("Maryland", "Big Ten", "5");
        private Team Memphis = new Team("Memphis", "AAC", "101");
        private Team MiamiFl = new Team("Miami(FL)", "ACC", "11");
        private Team MiamiOh = new Team("Miami(OH)", "MAC", "53");
        private Team Michigan = new Team("Michigan", "Big Ten", "29");
        private Team MichiganState = new Team("Michigan State", "Big Ten", "30");
        private Team MiddleTennesseeState = new Team("Middle Tennessee State", "CUSA", "152");
        private Team Minnesota = new Team("Minnesota", "Big Ten", "31");
        private Team MississippiState = new Team("Mississippi State", "SEC", "78");
        private Team Missouri = new Team("Missouri", "SEC", "22");
        private Team Navy = new Team("Navy", "Independent", "102");
        private Team Nebraska = new Team("Nebraska", "Big Ten", "23");
        private Team Nevada = new Team("Nevada", "MWC", "39");
        private Team NewMexico = new Team("New Mexico", "MWC", "92");
        private Team NewMexicoState = new Team("New Mexico State", "Sun Belt", "41");
        private Team NorthCarolina = new Team("North Carolina", "ACC", "6");
        private Team NCState = new Team("NC State", "ACC", "7");
        private Team NorthTexas = new Team("North Texas", "CUSA", "182");
        private Team NorthernIllinois = new Team("Northern Illinois", "MAC", "42");
        private Team Northwestern = new Team("Northwestern", "Big Ten", "32");
        private Team NotreDame = new Team("Notre Dame", "Independent", "104");
        private Team Ohio = new Team("Ohio", "MAC", "54");
        private Team OhioState = new Team("Ohio State", "Big Ten", "33");
        private Team Oklahoma = new Team("Oklahoma", "Big 12", "24");
        private Team OklahomaState = new Team("Oklahoma State", "Big 12", "25");
        private Team OldDominion = new Team("Old Dominion", "CUSA", "2371");
        private Team OleMiss = new Team("Ole Miss", "SEC", "77");
        private Team Oregon = new Team("Oregon", "Pac 12", "60");
        private Team OregonState = new Team("Oregon State", "Pac 12", "61");
        private Team PennState = new Team("Penn State", "Big Ten", "34");
        private Team Pittsburgh = new Team("Pittsburgh", "ACC", "12");
        private Team Purdue = new Team("Purdue", "Big Ten", "35");
        private Team Rice = new Team("Rice", "CUSA", "81");
        private Team Rutgers = new Team("Rutgers", "Big Ten", "13");
        private Team SanDiegoState = new Team("San Diego State", "MWC", "93");
        private Team SanJoseState = new Team("San Jose State", "MWC", "44");
        private Team SMU = new Team("SMU", "AAC", "82");
        private Team SouthAlabama = new Team("South Alabama", "South Alabama", "2549");
        private Team SouthCarolina = new Team("South Carolina", "SEC", "70");
        private Team SouthFlorida = new Team("South Florida", "AAC", "1019");
        private Team SouthernMiss = new Team("Southern Miss", "CUSA", "105");
        private Team Stanford = new Team("Stanford", "Pac 12", "63");
        private Team Syracuse = new Team("Syracuse", "ACC", "14");
        private Team TCU = new Team("TCU", "Big 12", "85");
        private Team Temple = new Team("Temple", "AAC", "15");
        private Team Tennessee = new Team("Tennessee", "SEC", "71");
        private Team Texas = new Team("Texas", "Big 12", "83");
        private Team TexasAM = new Team("Texas A&M", "SEC", "84");
        private Team TexasState = new Team("Texas State", "Sun Belt", "185");
        private Team TexasTech = new Team("Texas Tech", "Big 12", "86");
        private Team Toledo = new Team("Toledo", "MAC", "55");
        private Team Troy = new Team("Troy", "Sun Belt", "222");
        private Team Tulane = new Team("Tulane", "AAC", "106");
        private Team Tulsa = new Team("Tulsa", "AAC", "107");
        private Team UAB = new Team("UAB", "CUSA", "207");
        private Team UCF = new Team("Central Florida", "AAC", "210");
        private Team UCLA = new Team("UCLA", "Pac 12", "64");
        private Team UMass = new Team("UMass", "MAC", "204");
        private Team UNLV = new Team("UNLV", "MWC", "40");
        private Team USC = new Team("USC", "Pac 12", "62");
        private Team Utah = new Team("Utah", "Pac 12", "94");
        private Team UtahState = new Team("Utah State", "MWC", "46");
        private Team UTEP = new Team("UTEP", "CUSA", "95");
        private Team UTSA = new Team("UTSA", "CUSA", "2560");
        private Team Vanderbilt = new Team("Vanderbilt", "SEC", "72");
        private Team Virginia = new Team("Virginia", "ACC", "8");
        private Team VirginiaTech = new Team("Virginia Tech", "ACC", "16");
        private Team WakeForest = new Team("Wake Forest", "ACC", "9");
        private Team Washington = new Team("Washington", "Pac 12", "65");
        private Team WashingtonState = new Team("Washington State", "Pac 12", "66");
        private Team WestVirgnia = new Team("West Virginia", "Big 12", "17");
        private Team WesternKentucky = new Team("Western Kentucky", "CUSA", "224");
        private Team WesternMichigan = new Team("Western Michigan", "MAC", "56");
        private Team Wisconsin = new Team("Wisconsin", "Big Ten", "36");
        private Team Wyoming = new Team("Wyoming", "MWC", "96");
        private Conference AAC = new Conference("AAC");
        private Conference ACC = new Conference("ACC");
        private Conference Big12 = new Conference("Big 12");
        private Conference BigTen = new Conference("Big Ten");
        private Conference CUSA = new Conference("CUSA");
        private Conference independent = new Conference("Independent");
        private Conference MAC = new Conference("MAC");
        private Conference MWC = new Conference("MWC");
        private Conference Pac12 = new Conference("Pac 12");
        private Conference SEC = new Conference("SEC");
        private Conference SunBelt = new Conference("Sun Belt");

        //FCS Teams
        private Team AbileneChr = new Team("Abilene Christian", "FCS", "276");
        private Team AlabamaAM = new Team("Alabama A&M", "FCS", "356");
        private Team AlabamaSt = new Team("Alabama State", "FCS", "187");
        private Team Albany = new Team("Albany", "FCS", "546");
        private Team AlcornSt = new Team("Alcorn State", "FCS", "188");
        private Team ArkansasPB = new Team("Arkansas Pine Bluff", "FCS", "589");
        private Team AustinPeay = new Team("Austin Peay", "FCS", "150");
        private Team BethCook = new Team("Bethune Cookman", "FCS", "143");
        private Team Brown = new Team("Brown", "FCS", "127");
        private Team Bryant = new Team("Bryant", "FCS", "1948");
        private Team Bucknell = new Team("Bucknell", "FCS", "159");
        private Team Butler = new Team("Butler", "FCS", "165");
        private Team CalPoly = new Team("Cal Poly", "FCS", "108");
        private Team Campbell = new Team("Campbell", "FCS", "2357");
        private Team CentArk = new Team("Central Arkansas", "FCS", "268");
        private Team CentConn = new Team("Central Connecticut", "FCS", "209");
        private Team CharlestonSo = new Team("Charleston Southern", "FCS", "211");
        private Team Chattanooga = new Team("Chattanooga", "FCS", "177");
        private Team Citadel = new Team("The Citadel", "FCS", "172");
        private Team Colgate = new Team("Colgate", "FCS", "160");
        private Team Columbia = new Team("Columbia", "FCS", "128");
        private Team Cornell = new Team("Cornell", "FCS", "129");
        private Team Dartmouth = new Team("Dartmouth", "FCS", "130");
        private Team Davidson = new Team("Davidson", "FCS", "212");
        private Team Dayton = new Team("Dayton", "FCS", "166");
        private Team Delaware = new Team("Delaware", "FCS", "195");
        private Team DelawareSt = new Team("Delaware State", "FCS", "144");
        private Team Drake = new Team("Drake", "FCS", "167");
        private Team Duquesne = new Team("Duquesne", "FCS", "136");
        private Team EastTennSt = new Team("East Tennessee State", "FCS", "173");
        private Team EasternIll = new Team("Eastern Illinois", "FCS", "120");
        private Team EasternKent = new Team("Eastern Kentucky", "FCS", "151");
        private Team EasternWash = new Team("Eastern Washington", "FCS", "113");
        private Team Elon = new Team("Elon", "FCS", "350");
        private Team FloridaAM = new Team("Florida A&M", "FCS", "145");
        private Team Fordham = new Team("Fordham", "FCS", "161");
        private Team Furman = new Team("Furman", "FCS", "174");
        private Team GardnerWebb = new Team("Gardner Webb", "FCS", "351");
        private Team Georgetown = new Team("Georgetown", "FCS", "137");
        private Team GramblingSt = new Team("Grambling State", "FCS", "189");
        private Team Hampton = new Team("Hampton", "FCS", "229");
        private Team Harvard = new Team("Harvard", "FCS", "131");
        private Team HolyCross = new Team("Holy Cross", "FCS", "162");
        private Team HoustonBaptist = new Team("Houston Baptist", "FCS", "2601");
        private Team Howard = new Team("Howard", "FCS", "146");
        private Team IdahoSt = new Team("Idaho State", "FCS", "115");
        private Team IllinoisSt = new Team("Illinois State", "FCS", "121");
        private Team IncarnateWord = new Team("Incarnate Word", "FCS", "2539");
        private Team IndianaSt = new Team("Indiana State", "FCS", "122");
        private Team JacksonState = new Team("Jackson State", "FCS", "190");
        private Team Jacksonville = new Team("Jacksonville", "FCS", "2001");
        private Team JacksonvilleSt = new Team("Jacksonville State", "FCS", "247");
        private Team JamesMadison = new Team("James Madison", "FCS", "196");
        private Team KennesawSt = new Team("Kennesaw State", "FCS", "2610");
        private Team Lafayette = new Team("Lafayette", "FCS", "163");
        private Team Lamar = new Team("Lamar", "FCS", "2559");
        private Team Lehigh = new Team("Lehigh", "FCS", "164");
        private Team Liberty = new Team("Liberty", "FCS", "215");
        private Team Maine = new Team("Maine", "FCS", "203");
        private Team Marist = new Team("Marist", "FCS", "139");
        private Team McNeeseSt = new Team("McNeese State", "FCS", "180");
        private Team Mercer = new Team("Mercer", "FCS", "2597");
        private Team MissVallSt = new Team("Mississippi Valley State", "FCS", "191");
        private Team MissouriSt = new Team("Missouri State", "FCS", "125");
        private Team Monmouth = new Team("Monmouth", "FCS", "216");
        private Team Montana = new Team("Montana", "FCS", "116");
        private Team MontanaState = new Team("Montana State", "FCS", "117");
        private Team MoreheadSt = new Team("Morehead State", "FCS", "153");
        private Team MorganSt = new Team("Morgan State", "FCS", "147");
        private Team MurrayState = new Team("Murray State", "FCS", "154");
        private Team NewHamphshire = new Team("New Hampshire", "FCS", "205");
        private Team NichollsSt = new Team("Nicholls State", "FCS", "181");
        private Team NorfolkSt = new Team("Norfolk State", "FCS", "233");
        private Team NorthCarAT = new Team("North Carolina A&T", "FCS", "148");
        private Team NCCentral = new Team("NC Central", "FCS", "621");
        private Team NorthDakota = new Team("North Dakota", "FCS", "308");
        private Team NorthDakotaSt = new Team("North Dakota State", "FCS", "309");
        private Team NorthernArizona = new Team("Northern Arizona", "FCS", "118");
        private Team NorthernColorado = new Team("Northern Colorado", "FCS", "310");
        private Team NorthernIowa = new Team("Northern Iowa", "FCS", "123");
        private Team NorthwesternSt = new Team("Northwestern State", "FCS", "183");
        private Team Penn = new Team("Penn", "FCS", "132");
        private Team PortlandSt = new Team("Portland State", "FCS", "257");
        private Team PrairieViewAM = new Team("Prairie View A&M", "FCS", "192");
        private Team Presbyterian = new Team("Presbyterian", "FCS", "354");
        private Team Princeton = new Team("Princeton", "FCS", "133");
        private Team RhodeIsland = new Team("Rhode Island", "FCS", "206");
        private Team Richmond = new Team("Richmond", "FCS", "198");
        private Team RobertMorris = new Team("Robert Morris", "FCS", "217");
        private Team SacramentoSt = new Team("Sacramento State", "FCS", "110");
        private Team SacredHeart = new Team("Sacred Heart", "FCS", "259");
        private Team StFrancis = new Team("Saint Francis", "FCS", "219");
        private Team SamHoustonSt = new Team("Sam Houston State", "FCS", "184");
        private Team Samford = new Team("Samford", "FCS", "218");
        private Team SanDiego = new Team("San Diego", "FCS", "169");
        private Team SavannahSt = new Team("Savannah State", "FCS", "363");
        private Team SCState = new Team("South Carolina State", "FCS", "149");
        private Team SouthDakota = new Team("South Dakota", "FCS", "311");
        private Team SouthDakotaSt = new Team("South Dakota State", "FCS", "312");
        private Team SEMOSt = new Team("Southeast Missouri State", "FCS", "155");
        private Team SoutheastLa = new Team("Southeastern Louisiana", "FCS", "2234");
        private Team Southern = new Team("Southern", "FCS", "193");
        private Team SouthernIll = new Team("Southern Illinois", "FCS", "124");
        private Team SouthernUtah = new Team("Southern Utah", "FCS", "111");
        private Team StephenFAustin = new Team("Stephen F. Austin", "FCS", "186");
        private Team Stetson = new Team("Stetson", "FCS", "2598");
        private Team StonyBrook = new Team("Stony Brook", "FCS", "629");
        private Team TennesseeSt = new Team("Tennessee State", "FCS", "157");
        private Team TennesseeTech = new Team("Tennessee Tech", "FCS", "158");
        private Team TexasSouthern = new Team("Texas Southern", "FCS", "194");
        private Team Towson = new Team("Towson", "FCS", "221");
        private Team UCDavis = new Team("UC Davis", "FCS", "263");
        private Team TennMartin = new Team("Tennessee Martin", "FCS", "156");
        private Team Valparaiso = new Team("Valparaiso", "FCS", "170");
        private Team Villanova = new Team("Villanova", "FCS", "199");
        private Team VMI = new Team("Virginia Military", "FCS", "178");
        private Team Wagner = new Team("Wagner", "FCS", "223");
        private Team WeberState = new Team("Weber State", "FCS", "119");
        private Team WCarolina = new Team("Western Carolina", "FCS", "179");
        private Team WesternIll = new Team("Western Illinois", "FCS", "126");
        private Team WilliamMary = new Team("William & Mary", "FCS", "200");
        private Team Wofford = new Team("Wofford", "FCS", "267");
        private Team Yale = new Team("Yale", "FCS", "134");
        private Team YoungstownSt = new Team("Youngstown State", "FCS", "225");
        private Conference AA = new Conference("FCS");

        /// <summary>
        /// Adds all teams to the lists for their proper subdivision, and adds each
        /// conference to the list of conferences
        /// </summary>
        public NCAA()
        {
            FBS.Add(AirForce);
            FBS.Add(Akron);
            FBS.Add(Alabama);
            FBS.Add(AppalachianState);
            FBS.Add(Arizona);
            FBS.Add(ArizonaState);
            FBS.Add(Arkansas);
            FBS.Add(ArkansasState);
            FBS.Add(Army);
            FBS.Add(Auburn);
            FBS.Add(BallState);
            FBS.Add(Baylor);
            FBS.Add(BoiseState);
            FBS.Add(BostonCollege);
            FBS.Add(BowlingGreen);
            FBS.Add(Buffalo);
            FBS.Add(BYU);
            FBS.Add(California);
            FBS.Add(CentralMichigan);
            FBS.Add(Charlotte);
            FBS.Add(Cincinnati);
            FBS.Add(Clemson);
            FBS.Add(CoastalCarolina);
            FBS.Add(Colorado);
            FBS.Add(ColoradoState);
            FBS.Add(Connecticut);
            FBS.Add(Duke);
            FBS.Add(EastCarolina);
            FBS.Add(EasternMichigan);
            FBS.Add(Florida);
            FBS.Add(FloridaAtlantic);
            FBS.Add(FloridaInternational);
            FBS.Add(FloridaState);
            FBS.Add(FresnoState);
            FBS.Add(Georgia);
            FBS.Add(GeorgiaSouthern);
            FBS.Add(GeorgiaState);
            FBS.Add(GeorgiaTech);
            FBS.Add(Hawaii);
            FBS.Add(Houston);
            FBS.Add(Idaho);
            FBS.Add(Illinois);
            FBS.Add(Indiana);
            FBS.Add(Iowa);
            FBS.Add(IowaState);
            FBS.Add(Kansas);
            FBS.Add(KansasState);
            FBS.Add(KentState);
            FBS.Add(Kentucky);
            FBS.Add(LouisianaTech);
            FBS.Add(LouisianaLafayette);
            FBS.Add(LouisianaMonroe);
            FBS.Add(Louisville);
            FBS.Add(LSU);
            FBS.Add(Marshall);
            FBS.Add(Maryland);
            FBS.Add(Memphis);
            FBS.Add(MiamiFl);
            FBS.Add(MiamiOh);
            FBS.Add(Michigan);
            FBS.Add(MichiganState);
            FBS.Add(MiddleTennesseeState);
            FBS.Add(Minnesota);
            FBS.Add(MississippiState);
            FBS.Add(Missouri);
            FBS.Add(Navy);
            FBS.Add(Nebraska);
            FBS.Add(Nevada);
            FBS.Add(NewMexico);
            FBS.Add(NewMexicoState);
            FBS.Add(NorthCarolina);
            FBS.Add(NCState);
            FBS.Add(NorthTexas);
            FBS.Add(NorthernIllinois);
            FBS.Add(Northwestern);
            FBS.Add(NotreDame);
            FBS.Add(Ohio);
            FBS.Add(OhioState);
            FBS.Add(Oklahoma);
            FBS.Add(OklahomaState);
            FBS.Add(OldDominion);
            FBS.Add(OleMiss);
            FBS.Add(Oregon);
            FBS.Add(OregonState);
            FBS.Add(PennState);
            FBS.Add(Pittsburgh);
            FBS.Add(Purdue);
            FBS.Add(Rice);
            FBS.Add(Rutgers);
            FBS.Add(SanDiegoState);
            FBS.Add(SanJoseState);
            FBS.Add(SMU);
            FBS.Add(SouthAlabama);
            FBS.Add(SouthCarolina);
            FBS.Add(SouthFlorida);
            FBS.Add(SouthernMiss);
            FBS.Add(Stanford);
            FBS.Add(Syracuse);
            FBS.Add(TCU);
            FBS.Add(Temple);
            FBS.Add(Tennessee);
            FBS.Add(Texas);
            FBS.Add(TexasAM);
            FBS.Add(TexasState);
            FBS.Add(TexasTech);
            FBS.Add(Toledo);
            FBS.Add(Troy);
            FBS.Add(Tulane);
            FBS.Add(Tulsa);
            FBS.Add(UAB);
            FBS.Add(UCF);
            FBS.Add(UCLA);
            FBS.Add(UMass);
            FBS.Add(UNLV);
            FBS.Add(USC);
            FBS.Add(Utah);
            FBS.Add(UtahState);
            FBS.Add(UTEP);
            FBS.Add(UTSA);
            FBS.Add(Vanderbilt);
            FBS.Add(Virginia);
            FBS.Add(VirginiaTech);
            FBS.Add(WakeForest);
            FBS.Add(Washington);
            FBS.Add(WashingtonState);
            FBS.Add(WestVirgnia);
            FBS.Add(WesternKentucky);
            FBS.Add(WesternMichigan);
            FBS.Add(Wisconsin);
            FBS.Add(Wyoming);
            Conferences.Add(AAC);
            Conferences.Add(ACC);
            Conferences.Add(Big12);
            Conferences.Add(BigTen);
            Conferences.Add(CUSA);
            Conferences.Add(independent);
            Conferences.Add(MAC);
            Conferences.Add(MWC);
            Conferences.Add(Pac12);
            Conferences.Add(SEC);
            Conferences.Add(SunBelt);

            FCS.Add(AbileneChr);
            FCS.Add(AlabamaAM);
            FCS.Add(AlabamaSt);
            FCS.Add(Albany);
            FCS.Add(AlcornSt);
            FCS.Add(ArkansasPB);
            FCS.Add(AustinPeay);
            FCS.Add(BethCook);
            FCS.Add(Brown);
            FCS.Add(Bryant);
            FCS.Add(Bucknell);
            FCS.Add(Butler);
            FCS.Add(CalPoly);
            FCS.Add(Campbell);
            FCS.Add(CentArk);
            FCS.Add(CentConn);
            FCS.Add(CharlestonSo);
            FCS.Add(Chattanooga);
            FCS.Add(Citadel);
            FCS.Add(Colgate);
            FCS.Add(Columbia);
            FCS.Add(Cornell);
            FCS.Add(Dartmouth);
            FCS.Add(Davidson);
            FCS.Add(Dayton);
            FCS.Add(Delaware);
            FCS.Add(DelawareSt);
            FCS.Add(Drake);
            FCS.Add(Duquesne);
            FCS.Add(EastTennSt);
            FCS.Add(EasternIll);
            FCS.Add(EasternKent);
            FCS.Add(EasternWash);
            FCS.Add(Elon);
            FCS.Add(FloridaAM);
            FCS.Add(Fordham);
            FCS.Add(Furman);
            FCS.Add(GardnerWebb);
            FCS.Add(Georgetown);
            FCS.Add(GramblingSt);
            FCS.Add(Hampton);
            FCS.Add(Harvard);
            FCS.Add(HolyCross);
            FCS.Add(HoustonBaptist);
            FCS.Add(Howard);
            FCS.Add(IdahoSt);
            FCS.Add(IllinoisSt);
            FCS.Add(IncarnateWord);
            FCS.Add(IndianaSt);
            FCS.Add(JacksonState);
            FCS.Add(Jacksonville);
            FCS.Add(JacksonvilleSt);
            FCS.Add(JamesMadison);
            FCS.Add(KennesawSt);
            FCS.Add(Lafayette);
            FCS.Add(Lamar);
            FCS.Add(Lehigh);
            FCS.Add(Liberty);
            FCS.Add(Maine);
            FCS.Add(Marist);
            FCS.Add(McNeeseSt);
            FCS.Add(Mercer);
            FCS.Add(MissVallSt);
            FCS.Add(MissouriSt);
            FCS.Add(Monmouth);
            FCS.Add(Montana);
            FCS.Add(MontanaState);
            FCS.Add(MoreheadSt);
            FCS.Add(MorganSt);
            FCS.Add(MurrayState);
            FCS.Add(NewHamphshire);
            FCS.Add(NichollsSt);
            FCS.Add(NorfolkSt);
            FCS.Add(NorthCarAT);
            FCS.Add(NCCentral);
            FCS.Add(NorthDakota);
            FCS.Add(NorthDakotaSt);
            FCS.Add(NorthernArizona);
            FCS.Add(NorthernColorado);
            FCS.Add(NorthernIowa);
            FCS.Add(NorthwesternSt);
            FCS.Add(Penn);
            FCS.Add(PortlandSt);
            FCS.Add(PrairieViewAM);
            FCS.Add(Presbyterian);
            FCS.Add(Princeton);
            FCS.Add(RhodeIsland);
            FCS.Add(Richmond);
            FCS.Add(RobertMorris);
            FCS.Add(SacramentoSt);
            FCS.Add(SacredHeart);
            FCS.Add(StFrancis);
            FCS.Add(SamHoustonSt);
            FCS.Add(Samford);
            FCS.Add(SanDiego);
            FCS.Add(SavannahSt);
            FCS.Add(SCState);
            FCS.Add(SouthDakota);
            FCS.Add(SouthDakotaSt);
            FCS.Add(SoutheastLa);
            FCS.Add(SEMOSt);
            FCS.Add(Southern);
            FCS.Add(SouthernIll);
            FCS.Add(SouthernUtah);
            FCS.Add(StephenFAustin);
            FCS.Add(Stetson);
            FCS.Add(StonyBrook);
            FCS.Add(TennesseeSt);
            FCS.Add(TennesseeTech);
            FCS.Add(TexasSouthern);
            FCS.Add(Towson);
            FCS.Add(UCDavis);
            FCS.Add(TennMartin);
            FCS.Add(Valparaiso);
            FCS.Add(Villanova);
            FCS.Add(VMI);
            FCS.Add(Wagner);
            FCS.Add(WeberState);
            FCS.Add(WCarolina);
            FCS.Add(WesternIll);
            FCS.Add(WilliamMary);
            FCS.Add(Wofford);
            FCS.Add(Yale);
            FCS.Add(YoungstownSt);

            Conferences.Add(AA);
        }

        /// <summary>
        /// Gets the list of FBS teams
        /// </summary>
        /// <returns>the list of FBS teams</returns>
        public List<Team> GetFBS()
        {
            return FBS;
        }

        /// <summary>
        /// Gets the list of FCS teams
        /// </summary>
        /// <returns>the list of FCS teams</returns>
        public List<Team> GetFCS()
        {
            return FCS;
        }

        /// <summary>
        /// Gets the list of conferences
        /// </summary>
        /// <returns>the list of conferences</returns>
        public List<Conference> GetConferences()
        {
            return Conferences;
        }
    }
}
